version: "3"
services:
  frontend:
    build: ./frontend
    image: lemos12/frontend-crud-avaliada-4-m7
    ports:
      - "3000:3000"
    restart: always

  backend:
    build: ./backend
    image: lemos12/backend-crud-avaliada-4-m7
    ports:
      - "3001:3001"
    volumes:
      - .:/backend
    restart: always

  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_DB: "API-CRUD"
  #     POSTGRES_USER: "user"
  #     POSTGRES_PASSWORD: "password"
  #   expose:
  #     - "5432"
  #   ports:
  #     - "3002:5432"
  #   volumes:
  #     # So that our database's state is persisted locally
  #     - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  #     # Where our data will be persisted
  #     - my-db:/var/lib/posgresql

# Names our volume
volumes:
  my-db:
